test_that("sim methods work", {
  set.seed(42)
  L <- fastclime.generator(n = 50, d = 10, graph = "band", g = 2, vis = FALSE)

  # Ensure the object belongs to 'sim' class
  expect_s3_class(L, "sim")

  # Test print method
  expect_output(print(L$data)) # Base print to compare
  expect_output(print(L), "Simulated data generated by fastclime.generator()")

  # plot.sim testing
  # we cannot easily test the graphical output itself, but we can verify it runs without error
  # It depends on igraph for plotting
  expect_error(plot(L), NA) # NA error means it should pass without error
})

test_that("fastclime.selector edge cases", {
  set.seed(42)
  L = fastclime.generator(n = 50, d = 10, vis = FALSE)
  out = fastclime(L$data, 0.1, nlambda = 10)

  # Edge case: Very LOW lambda where nodes don't reach target
  # Expected a warning: "Some columns do not reach the required lambda!"
  expect_warning(
    fastclime.selector(out$lambdamtx, out$icovlist, 0.0001),
    "Some columns do not reach the required lambda!"
  )
})
