#-------------------------------------------------------------------------------#
# Package: fastclime                                                            #
# fastclime.generator(): Data generator                                         #
# Authors: Haotian Pang, Han Liu and Robert Vanderbei                           #
# Emails: <hpang@princeton.edu>, <hanliu@princeton.edu> and <rvdb@princetonedu> #
# Date: April 22nd 2016                                                         #
# Version: 1.4.1					                                            #
#-------------------------------------------------------------------------------#

#' @title Data Generator for Fastclime
#' @description Generates synthetic data for testing fastclime
#' @export

## Main function
fastclime.generator = function(
  n = 200,
  d = 50,
  graph = "random",
  v = NULL,
  u = NULL,
  g = NULL,
  prob = NULL,
  vis = FALSE,
  verbose = TRUE
) {
  # Note: Removed manual gc() calls as they severely degrade performance.
  gcinfo(FALSE)
  if (verbose) {
    message(
      "Generating data from the multivariate normal distribution with the ",
      graph,
      " graph structure...."
    )
  }
  if (is.null(g)) {
    g = 1
    if (graph == "hub" || graph == "cluster") {
      if (d > 40) {
        g = ceiling(d / 20)
      }
      if (d <= 40) g = 2
    }
  }

  if (graph == "random") {
    if (is.null(prob)) {
      prob = min(1, 3 / d)
    }
    prob = sqrt(prob / 2) *
      (prob < 0.5) +
      (1 - sqrt(0.5 - 0.5 * prob)) * (prob >= 0.5)
  }

  if (graph == "cluster") {
    if (is.null(prob)) {
      if (d / g > 30) {
        prob = 0.3
      }
      if (d / g <= 30) prob = min(1, 6 * g / d)
    }
    prob = sqrt(prob / 2) *
      (prob < 0.5) +
      (1 - sqrt(0.5 - 0.5 * prob)) * (prob >= 0.5)
  }

  # parition variables into groups
  g.large = d %% g
  g.small = g - g.large
  n.small = floor(d / g)
  n.large = n.small + 1
  g.list = c(rep(n.small, g.small), rep(n.large, g.large))
  g.ind = rep(c(1:g), g.list)
  rm(g.large, g.small, n.small, n.large, g.list)

  # build the graph structure
  theta = matrix(0, d, d)
  if (graph == "band") {
    if (is.null(u)) {
      u = 0.1
    }
    if (is.null(v)) {
      v = 0.3
    }
    for (i in 1:g) {
      diag(theta[1:(d - i), (1 + i):d]) = 1
      diag(theta[(1 + i):d, 1:(d - i)]) = 1
    }
  }
  if (graph == "cluster") {
    if (is.null(u)) {
      u = 0.1
    }
    if (is.null(v)) {
      v = 0.3
    }
    for (i in 1:g) {
      tmp = which(g.ind == i)
      tmp2 = matrix(runif(length(tmp)^2, 0, 0.5), length(tmp), length(tmp))
      tmp2 = tmp2 + t(tmp2)
      theta[tmp, tmp][tmp2 < prob] = 1
      rm(tmp, tmp2)
    }
  }
  if (graph == "hub") {
    if (is.null(u)) {
      u = 0.1
    }
    if (is.null(v)) {
      v = 0.3
    }
    for (i in 1:g) {
      tmp = which(g.ind == i)
      theta[tmp[1], tmp] = 1
      theta[tmp, tmp[1]] = 1
      rm(tmp)
    }
  }
  if (graph == "random") {
    if (is.null(u)) {
      u = 0.1
    }
    if (is.null(v)) {
      v = 0.3
    }

    tmp = matrix(runif(d^2, 0, 0.5), d, d)
    tmp = tmp + t(tmp)
    theta[tmp < prob] = 1
    #theta[tmp >= tprob] = 0
    rm(tmp)
  }

  diag(theta) = 0
  omega = theta * v

  # make omega positive definite and standardized
  diag(omega) = abs(min(eigen(omega)$values)) + 0.1 + u
  sigma = cov2cor(solve(omega))
  omega = solve(sigma)

  # generate multivariate normal data
  x = mvrnorm(n, rep(0, d), sigma)

  sigmahat = cov(x) * (1 - 1 / n)

  # graph and covariance visulization
  if (vis == TRUE) {
    old_par <- par(
      mfrow = c(2, 2),
      pty = "s",
      omi = c(0.3, 0.3, 0.3, 0.3),
      mai = c(0.3, 0.3, 0.3, 0.3)
    )
    on.exit(par(old_par), add = TRUE)

    image(theta, col = gray.colors(256), main = "Adjacency Matrix")

    image(
      sigma,
      col = gray.colors(256),
      main = "Covariance Matrix"
    )
    g <- graph_from_adjacency_matrix(theta, mode = "undirected", diag = FALSE)
    layout.grid <- layout_with_fr(g)

    plot(
      g,
      layout = layout.grid,
      edge.color = 'gray50',
      vertex.color = "red",
      vertex.size = 3,
      vertex.label = NA,
      main = "Graph Pattern"
    )

    image(
      sigmahat,
      col = gray.colors(256),
      main = "Empirical Matrix"
    )
  }
  if (verbose) {
    message("done.")
  }
  rm(vis, verbose)

  sim = list(
    data = x,
    sigma = sigma,
    sigmahat = sigmahat,
    omega = omega,
    theta = Matrix(theta, sparse = TRUE),
    sparsity = sum(theta) / (d * (d - 1)),
    graph.type = graph
  )
  class(sim) = "sim"
  return(sim)
}

#' @export
print.sim <- function(x, ...) {
  if (!is.null(x$graph.type)) {
    cat("Simulated data generated by fastclime.generator()\n")
    cat("Sample size: n =", nrow(x$data), "\n")
    cat("Dimension: d =", ncol(x$data), "\n")
    cat("Graph type =", x$graph.type, "\n")
    cat(
      "Sparsity level:",
      round(sum(x$theta) / ncol(x$data) / (ncol(x$data) - 1), 4),
      "\n"
    )
  } else if (!is.null(x$X0)) {
    cat("Simulated data generated by dantzig.generator()\n")
    cat("Sample size: n =", nrow(x$X0), "\n")
    cat("Dimension: d =", ncol(x$X0), "\n")
    cat("True sparsity:", x$s, "\n")
  } else {
    cat("Simulated data\n")
  }
  invisible(x)
}

#' @export
plot.sim <- function(x, ...) {
  if (is.null(x$theta)) {
    stop("plot.sim can only plot output from fastclime.generator")
  }
  gcinfo(FALSE)
  old_par <- par(
    mfrow = c(2, 2),
    pty = "s",
    omi = c(0.3, 0.3, 0.3, 0.3),
    mai = c(0.3, 0.3, 0.3, 0.3)
  )
  on.exit(par(old_par), add = TRUE)
  image(as.matrix(x$theta), col = gray.colors(256), main = "Adjacency Matrix")
  image(x$sigma, col = gray.colors(256), main = "Covariance Matrix")
  g <- graph_from_adjacency_matrix(x$theta, mode = "undirected", diag = FALSE)
  layout.grid <- layout_with_fr(g)

  plot(
    g,
    layout = layout.grid,
    edge.color = 'gray50',
    vertex.color = "red",
    vertex.size = 3,
    vertex.label = NA,
    main = "Graph Pattern"
  )

  image(
    x$sigmahat,
    col = gray.colors(256),
    main = "Empirical Covariance Matrix"
  )
}
